version: '3.7'

services:
  php:
    image: php:apache
    build: .
    ports:
      - "8087:80"
    volumes:
      - php_data:/var/www/html

  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=thegame
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=wp
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    depends_on:
       - db
    image: phpmyadmin/phpmyadmin
    ports:
      - "8089:80"
    links: 
      - db:db
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1015
      - 8025:8025
volumes:
  db_data: {}
  php_data: {}
